apiVersion: skaffold/v2alpha3
kind: Config
build:
  artifacts:
    - image: django-test
      context: django
      # sync:
      #   infer:
      #   - 'src/**/*.js'
deploy:
  kubectl:
    manifests:
      - ./*/kubernetes/*.yml
# portForward:
#   - resourceType: Service
#     resourceName: django-service
#     port: 8000
#     localPort: 8000
