apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-deployment
spec:
  selector:
    matchLabels:
      app: django
  replicas: 1
  template:
    metadata:
      labels:
        app: django
    spec:
      containers:
        - name: django
          image: django-test
          command: ["python3", "manage.py", "runserver", "0.0.0.0:8000"]
          ports:
            - containerPort: 8000
          env:
            - name: POSTGRES_HOST
              value: postgres-service
      initContainers:
        - name: init-db-check
          image: django-test
          env:
            - name: POSTGRES_HOST
              value: postgres-service
          command:
            - bash
            - ./db-ready.sh
        # - name: init-db-migrate
        #   image: django-test
        #   command: ["python3", "manage.py", "migrate"]
