# apiVersion: batch/v1
# kind: Job
# metadata:
#   name: django-migrations
# spec:
#   template:
#     spec:
#       containers:
#         - name: django-migrations
#           image: django-test
#           command: ["python3", "manage.py", "migrate"]
#           env:
#             - name: POSTGRES_HOST
#               value: postgres-service
#       restartPolicy: Never
#   backoffLimit: 1
